### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by remizik** [trmendes/waterydroid#1]
Edit : I'm stupid please ignore my issue, the feature is already present in the app.

**Comment by trmendes** [comment]
@remizik Don't worry :)....you are not stupid....the app is VERY, VERY, VERY simple.

PS:
I'm keeping the repository on gitlab so if you have any ideas or issues please, send me a message there :)

**Comment by remizik** [comment]
@trmendes It was RIGHT THERE under my nose lol. I'm so used to many settings menu in apps that I guess my brain gave up on such a simple but cool app haha.
Alright for your PS :)

**Comment by trmendes** [comment]
it happens :)

**Comment by remizik** [comment]
@trmendes I'm sorry to do this here but I'm completely lost on the GitLab website. I can't find issues/feature request for your app. So I'm going to write it here :/  

It would be nice to have the option to only have an audio notification and no visual notification. I would just love to hear a sound that reminds me to drink, I don't need to constantly clear the visual notification. If it's possible of course.  

Thanks :)
